version: '3.9'
services:
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./logs:/usr/src/fastapi_sample/logs
    environment:
      - TZ=Asia/Tokyo